### ISSUE TITLE
Test responsiveness through Google chrome devices

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/VignalEnChanson#4]

**Comment by WebDevJL** [comment]
Look into the high density pixel (Retina) devices (Kindle Fire HDX) as it doesn't look great...
![localhost-vec--wr kindle fire hdx](https://cloud.githubusercontent.com/assets/3506074/21962624/57cbc45c-db2a-11e6-9bf9-f2b476beeb34.png)

**Comment by over-e** [comment]
Bonjour
J'ai toujours des mails vignal.....

Le 15 janv. 2017 13:56, "Jérémie Litzler" <notifications@github.com> a
écrit :

Look into the high density pixel (Retina) devices (Kindle Fire HDX) as it
doesn't look great...
[image: localhost-vec--wr kindle fire hdx]
<https://cloud.githubusercontent.com/assets/3506074/21962624/57cbc45c-db2a-11e6-9bf9-f2b476beeb34.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Puzzlout/VignalEnChanson/issues/4#issuecomment-272693504>,
or mute the thread
